defmodule FindThemApiWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :findthem_api

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_findthem_api_key",
    signing_salt: "960WpCrt",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :findthem_api,
    gzip: not code_reloading?,
    only: FindThemApiWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :findthem_api
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # :multipart gets its own higher :length (Plug's default is 8MB for every
  # parser) to fit Photos' 10MB upload cap — :json/:urlencoded stay at the
  # default, no legitimate request body needs to be that large.
  plug Plug.Parsers,
    parsers: [:urlencoded, {:multipart, length: 11_000_000}, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  plug CORSPlug, origin: &FindThemApiWeb.Endpoint.cors_origins/0
  plug FindThemApiWeb.Router

  def cors_origins, do: Application.get_env(:findthem_api, :cors_origins, [])
end
